apiVersion: v1
kind: Namespace
metadata:
  name: tenant-b-100mi
  labels:
    name: development
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nsq
  namespace: tenant-b-100mi
spec:
  hard:
    limits.memory: 100Mi
