apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
   - name: myvolumes-container
     image: nginx
     volumeMounts:
      - name: pv
        mountPath: "/mnt/readonly"
  volumes:
   - name: pv
     persistentVolumeClaim:
       claimName: my-pvc
