apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jumppod-netpolicy
spec:
  podSelector:
    matchLabels:
      app: secure-app
  ingress:      
  - from:
    - podSelector:
        matchLabels:
          tier: jumppod
          #    ports:
          #    - port: 80 
